In [4]:
import pandas as pd
import numpy as np
from sklearn import decomposition
import matplotlib.pyplot as plt

In [23]:
dataset = pd.read_csv("roo_data.csv")

In [24]:
#dataset = dataset.iloc[:20000,:5].values



In [25]:
dataset

Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                            69                        63   
1                                            78                        62   
2                                            71                        86   
3                                            76                        87   
4                                            92                        62   
...                                         ...                       ...   
19995                                        83                        67   
19996                                        80                        69   
19997                                        83                        70   
19998                                        68                        87   
19999                                        73                        77   

       Percentage in Programming Concepts  Percentage in Software Engineering  \
0                                      78                                  87   
1                                      73                                  60   
2                                      91                                  87   
3                                      60                                  84   
4                                      90                                  67   
...                                   ...                                 ...   
19995                                  62                                  63   
19996                                  83                                  87   
19997                                  80                                  87   
19998                                  91                                  88   
19999                                  74                                  84   

       Percentage in Computer Networks  Percentage in Electronics Subjects  \
0                                   94                                  94   
1                                   71                                  70   
2                                   61                                  81   
3                                   89                                  73   
4                                   71                                  89   
...                                ...                                 ...   
19995                               81                                  74   
19996                               82                                  66   
19997                               64                                  85   
19998                               66                                  74   
19999                               70                                  65   

       Percentage in Computer Architecture  Percentage in Mathematics  \
0                                       87                         84   
1                                       73                         84   
2                                       72                         72   
3                                       62                         88   
4                                       73                         71   
...                                    ...                        ...   
19995                                   90                         84   
19996                                   66                         92   
19997                                   69                         94   
19998                                   61                         87   
19999                                   92                         73   

       Percentage in Communication skills  Hours working per day  ...  \
0                                      61                      9  ...   
1                                      91                     12  ...   
2                                      94                     11  ...   
3  

In [26]:
data = dataset.iloc[:,:-1].values
label = dataset.iloc[:,-1].values
len(data[0])

38

In [27]:
dataset.iloc[:,14:38]

can work long time before system? self-learning capability?  \
0                                   yes                       yes   
1                                   yes                        no   
2                                   yes                        no   
3                                    no                       yes   
4                                    no                        no   
...                                 ...                       ...   
19995                               yes                        no   
19996                               yes                        no   
19997                               yes                       yes   
19998                                no                        no   
19999                               yes                       yes   

      Extra-courses did        certifications          workshops  \
0                   yes     shell programming    cloud computing   
1                   yes      machine learning  database security   
2                   yes       app development   web technologies   
3                    no                python       data science   
4                    no       app development    cloud computing   
...                 ...                   ...                ...   
19995                no       app development    cloud computing   
19996                no            full stack   game development   
19997               yes  information security  database security   
19998                no            full stack    cloud computing   
19999               yes       app development  database security   

      talenttests taken? olympiads reading and writing skills  \
0                     no       yes                  excellent   
1                     no        no                       poor   
2                     no       yes                       poor   
3                    yes        no                     medium   
4                     no        no                       poor   
...                  ...       ...                        ...   
19995                yes        no                       poor   
19996                 no       yes                     medium   
19997                yes       yes                     medium   
19998                 no       yes                       poor   
19999                 no       yes                  excellent   

      memory capability score    Interested subjects  ... interested in games  \
0                   excellent        cloud computing  ...                  no   
1                      medium               networks  ...                 yes   
2                   excellent                hacking  ...                 yes   
3                   excellent               networks  ...                  no   
4                   excellent  Computer Architecture  ...                 yes   
...                       ...                    ...  ...                 ...   
19995               excellent   Software Engineering  ...                 yes   
19996               excellent             Management  ...                 yes   
19997               excellent               networks  ...                 yes   
19998                    poor                    IOT  ...                  no   
19999               excellent                    IOT  ...                  no   

      Interested Type of Books Salary Range Expected In a Realtionship?  \
0                 Prayer books                salary                 no   
1                    Childrens                salary                yes   
2                       Travel                  Work                 no   
3                      Romance                  Work                yes   
4                    Cookbooks                salary                 no   
...                        ...                   ...                ...   
19995                 Journals                  Work                yes   
19996 

In [28]:
dataset.iloc[:,:14]

Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                            69                        63   
1                                            78                        62   
2                                            71                        86   
3                                            76                        87   
4                                            92                        62   
...                                         ...                       ...   
19995                                        83                        67   
19996                                        80                        69   
19997                                        83                        70   
19998                                        68                        87   
19999                                        73                        77   

       Percentage in Programming Concepts  Percentage in Software Engineering  \
0                                      78                                  87   
1                                      73                                  60   
2                                      91                                  87   
3                                      60                                  84   
4                                      90                                  67   
...                                   ...                                 ...   
19995                                  62                                  63   
19996                                  83                                  87   
19997                                  80                                  87   
19998                                  91                                  88   
19999                                  74                                  84   

       Percentage in Computer Networks  Percentage in Electronics Subjects  \
0                                   94                                  94   
1                                   71                                  70   
2                                   61                                  81   
3                                   89                                  73   
4                                   71                                  89   
...                                ...                                 ...   
19995                               81                                  74   
19996                               82                                  66   
19997                               64                                  85   
19998                               66                                  74   
19999                               70                                  65   

       Percentage in Computer Architecture  Percentage in Mathematics  \
0                                       87                         84   
1                                       73                         84   
2                                       72                         72   
3                                       62                         88   
4                                       73                         71   
...                                    ...                        ...   
19995                                   90                         84   
19996                                   66                         92   
19997                                   69                         94   
19998                                   61                         87   
19999                                   92                         73   

       Percentage in Communication skills  Hours working per day  \
0                                      61                      9   
1                                      91                     12   
2                                      94                     11   
3                      

In [29]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [30]:
labelencoder = LabelEncoder()

In [31]:
for i in range(14,38):
    data[:,i] = labelencoder.fit_transform(data[:,i])
data[0]

array([69, 63, 78, 87, 94, 94, 87, 84, 61, 9, 4, 0, 4, 8, 1, 1, 1, 8, 0,
       0, 1, 0, 0, 4, 4, 0, 8, 0, 0, 21, 1, 0, 1, 0, 0, 0, 1, 0],
      dtype=object)

In [32]:
data[:5,14:]

array([[1, 1, 1, 8, 0, 0, 1, 0, 0, 4, 4, 0, 8, 0, 0, 21, 1, 0, 1, 0, 0,
        0, 1, 0],
       [1, 0, 1, 5, 2, 0, 0, 2, 1, 7, 0, 1, 4, 1, 1, 5, 1, 1, 0, 1, 0, 0,
        0, 1],
       [1, 0, 1, 0, 7, 0, 1, 2, 0, 6, 2, 0, 5, 1, 1, 29, 0, 0, 1, 0, 1,
        0, 0, 1],
       [0, 1, 0, 6, 1, 1, 0, 1, 0, 7, 5, 0, 7, 0, 0, 23, 0, 1, 0, 0, 1,
        1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 5, 0, 9, 0, 1, 7, 1, 0, 1, 0, 1, 0,
        1, 1]], dtype=object)

In [33]:
from sklearn.preprocessing import Normalizer

In [35]:
data1=data[:,:14]

In [36]:
normalized_data = Normalizer().fit_transform(data1)
print(normalized_data.shape)

(20000, 14)


In [37]:
normalized_data

array([[0.28508989, 0.26029947, 0.32227553, ..., 0.        , 0.01652695,
        0.0330539 ],
       [0.34997994, 0.27818918, 0.32754533, ..., 0.00448692, 0.00897384,
        0.01346077],
       [0.29501244, 0.35733901, 0.37811453, ..., 0.01662042, 0.0041551 ,
        0.01246531],
       ...,
       [0.3430836 , 0.28934762, 0.33068299, ..., 0.02480122, 0.00826707,
        0.01240061],
       [0.29479246, 0.37716094, 0.39450167, ..., 0.01734073, 0.03901665,
        0.02167592],
       [0.31140896, 0.32847247, 0.31567484, ..., 0.00426588, 0.02986113,
        0.02559526]])

In [38]:
data2=data[:,14:]
data2.shape

(20000, 24)

In [39]:
df1 = np.append(normalized_data,data2,axis=1)

df1.shape

(20000, 38)

## adding headers

In [40]:
X1 = pd.DataFrame(df1,columns=['Acedamic percentage in Operating Systems', 'percentage in Algorithms',
       'Percentage in Programming Concepts',
       'Percentage in Software Engineering', 'Percentage in Computer Networks',
       'Percentage in Electronics Subjects',
       'Percentage in Computer Architecture', 'Percentage in Mathematics',
       'Percentage in Communication skills', 'Hours working per day',
       'Logical quotient rating', 'hackathons', 'coding skills rating',
       'public speaking points', 'can work long time before system?',
       'self-learning capability?', 'Extra-courses did', 'certifications',
       'workshops', 'talenttests taken?', 'olympiads',
       'reading and writing skills', 'memory capability score',
       'Interested subjects', 'interested career area ', 'Job/Higher Studies?',
       'Type of company want to settle in?',
       'Taken inputs from seniors or elders', 'interested in games',
       'Interested Type of Books', 'Salary Range Expected',
       'In a Realtionship?', 'Gentle or Tuff behaviour?',
       'Management or Technical', 'Salary/work', 'hard/smart worker',
       'worked in teams ever?', 'Introvert'])

In [41]:
X1.head()

Acedamic percentage in Operating Systems percentage in Algorithms  \
0                                  0.28509                 0.260299   
1                                  0.34998                 0.278189   
2                                 0.295012                 0.357339   
3                                 0.328025                 0.375503   
4                                 0.397157                 0.267649   

  Percentage in Programming Concepts Percentage in Software Engineering  \
0                           0.322276                           0.359461   
1                           0.327545                           0.269215   
2                           0.378115                           0.361494   
3                           0.258967                           0.362554   
4                           0.388523                           0.289234   

  Percentage in Computer Networks Percentage in Electronics Subjects  \
0                        0.388383                           0.388383   
1                        0.318571                           0.314085   
2                        0.253461                           0.336563   
3                        0.384135                           0.315077   
4                        0.306502                           0.384206   

  Percentage in Computer Architecture Percentage in Mathematics  \
0                            0.359461                  0.347066   
1                            0.327545                  0.376901   
2                            0.299168                  0.299168   
3                              0.2676                  0.379819   
4                            0.315136                  0.306502   

  Percentage in Communication skills Hours working per day  ...  \
0                           0.252036             0.0371856  ...   
1                            0.40831             0.0538431  ...   
2                            0.39058             0.0457062  ...   
3                           0.297812             0.0302129  ...   
4                           0.315136             0.0172677  ...   

  interested in games Interested Type of Books Salary Range Expected  \
0                   0                       21                     1   
1                   1                        5                     1   
2                   1                       29                     0   
3                   0                       23                     0   
4                   1                        7                     1   

  In a Realtionship? Gentle or Tuff behaviour? Management or Technical  \
0                  0                         1                       0   
1                  1                         0                       1   
2                  0                         1                       0   
3                  1                         0                       0   
4                  0                         1                       0   

  Salary/work hard/smart worker worked in teams ever? Introvert  
0           0                 0                     1         0  
1           0                 0                     0         1  
2           1                 0                     0         1  
3           1                 1                     1         1  
4           1                 0                     1         1  

[5 rows x 38 columns]

In [42]:
label = labelencoder.fit_transform(label)
print(len(label))

20000


In [43]:
y=pd.DataFrame(label,columns=["Suggested Job Role"])
y.head()

Suggested Job Role
0                   7
1                  18
2                  18
3                  28
4                   2

# Decision Tree Classifier 

In [44]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import preprocessing 
from sklearn.metrics import accuracy_score

In [45]:
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.2,random_state=10) 

In [46]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

In [47]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [48]:
y_pred = clf.predict(X_test)

In [49]:
y_pred

array([24,  6, 15, ..., 23, 28, 28])

In [50]:
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)

In [51]:
cm

array([[3, 9, 3, ..., 3, 3, 4],
       [4, 4, 1, ..., 3, 2, 2],
       [5, 2, 2, ..., 2, 0, 6],
       ...,
       [6, 1, 2, ..., 2, 1, 5],
       [3, 4, 3, ..., 6, 3, 4],
       [5, 6, 2, ..., 2, 4, 1]], dtype=int64)

In [52]:
accuracy

0.02875

In [53]:
print("confusion matrics=",cm)
print("  ")
print("accuracy=",accuracy*100)

confusion matrics= [[3 9 3 ... 3 3 4]
 [4 4 1 ... 3 2 2]
 [5 2 2 ... 2 0 6]
 ...
 [6 1 2 ... 2 1 5]
 [3 4 3 ... 6 3 4]
 [5 6 2 ... 2 4 1]]
  
accuracy= 2.875


# Decision tree with entropy

In [89]:
clf_entropy = tree.DecisionTreeClassifier(criterion = "entropy", random_state = 42)
clf_entropy.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=42, splitter='best')

In [90]:
entropy_y_pred=clf_entropy.predict(X_test)

In [91]:
cm_entopy = confusion_matrix(y_test,entropy_y_pred)

In [92]:
entropy_accuracy = accuracy_score(y_test,entropy_y_pred)

In [93]:
print("confusion matrics=",cm_entopy)
print("  ")
print("accuracy=",entropy_accuracy*100)

confusion matrics= [[1 4 6 ... 4 6 5]
 [2 4 1 ... 1 3 5]
 [2 7 1 ... 0 3 6]
 ...
 [2 2 1 ... 4 2 2]
 [2 3 9 ... 3 4 1]
 [1 5 5 ... 5 6 2]]
  
accuracy= 2.875


# SVM (Support vector machine) classifier

In [59]:
from sklearn import svm

In [95]:
clf = svm.SVC()
clf.fit(X_train, y_train)

c:\users\kajanan\anaconda3\envs\cp\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [96]:
svm_y_pred = clf.predict(X_test)

In [97]:
svm_cm = confusion_matrix(y_test,svm_y_pred)
svm_accuracy = accuracy_score(y_test,svm_y_pred)

In [98]:
print("confusion matrics=",svm_cm)
print("  ")
print("accuracy=",svm_accuracy*100)

confusion matrics= [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
  
accuracy= 5.35


#  xgboost

# changing data type to int64

In [76]:
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.3,random_state=10) 

In [77]:
X_train.shape

(14000, 38)

In [64]:
X_train=pd.to_numeric(X_train.values.flatten())

In [66]:
X_train=X_train.reshape((16000,38))

In [71]:
from xgboost import XGBClassifier

In [72]:
model = XGBClassifier()
model.fit(X_train, y_train)

c:\users\kajanan\anaconda3\envs\cp\lib\site-packages\sklearn\preprocessing\_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\users\kajanan\anaconda3\envs\cp\lib\site-packages\sklearn\preprocessing\_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [73]:
xgb_y_pred = clf.predict(X_test)

In [74]:
xgb_cm = confusion_matrix(y_test,xgb_y_pred)
xgb_accuracy = accuracy_score(y_test,xgb_y_pred)


In [75]:
print("confusion matrics=",xgb_cm)
print("  ")
print("accuracy=",xgb_accuracy*100)

confusion matrics= [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
  
accuracy= 5.6000000000000005


In [99]:
#dimentionality redution
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.2,random_state=42) 
from sklearn.decomposition import PCA
pca = PCA(n_components=5)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)


In [100]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)
classifier.fit(X_train, y_train)


c:\users\kajanan\anaconda3\envs\cp\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=2, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [101]:
y_pred = classifier.predict(X_test)
svm_cm = confusion_matrix(y_test,svm_y_pred)
svm_accuracy = accuracy_score(y_test,svm_y_pred)

In [102]:
svm_accuracy

0.0535